### ISSUE TITLE
name claim is not working

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#75]
##Using version
```
commit 22e77952a1666d67b4dc2094b92fd33a3089f114
Merge: bce24f0 6f3ee1b
Author: Andrea Giacobino <no.andrea@gmail.com>
Date:   Tue Nov 6 17:51:29 2018 +0100

    Merge pull request #73 from aeternity/release/0.25.0.1b1

    Release/0.25.0.1b1
```

##Executing
```
(venv)# aecli account balance wallet
Enter the account password []:
<none>
  Balance ___________________________________________ 20000000000000000000
  Id ________________________________________________ ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg7VpZsw7
  Nonce _____________________________________________ 0
</none>

```
##This fails
```
(venv)# aecli name claim wallet kryztoval.test
Enter the account password []:
Traceback (most recent call last):
  File "/usr/bin/aecli", line 3, in <module>
    from aeternity import __main__
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 702, in <module>
    cli(obj={})
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/aepp-sdk-python/venv/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 343, in name_register
    txs = name.full_claim_blocking(account, name_ttl=name_ttl, tx_ttl=ttl)
  File "/opt/aepp-sdk-python/aeternity/aens.py", line 125, in full_claim_blocking
    h = self.preclaim(account, fee=preclaim_fee, tx_ttl=tx_ttl)
  File "/opt/aepp-sdk-python/aeternity/aens.py", line 151, in preclaim
    tx, sg, tx_hash = txb.tx_name_preclaim(commitment_hash, fee, tx_ttl)
  File "/opt/aepp-sdk-python/aeternity/transactions.py", line 266, in tx_name_preclaim
    tx = self.epoch.post_name_preclaim(body=body)
  File "/opt/aepp-sdk-python/aeternity/openapi.py", line 188, in api_method
    raise OpenAPIClientException(f"Error: {api_response.desc}", code=http_reply.status_code)
aeternity.openapi.OpenAPIClientException: Error: Account not found

```

**Comment by noandrea** [comment]
Hey @kryztoval  can you paste the output of

```
aecli --version 
```
and 
```
aecli config
```

**Comment by kryztoval** [comment]
I already said I was using commit "22e77952a1666d67b4dc2094b92fd33a3089f114", and the result of --version is: `aecli, version 0.25.0.1b1`

The result to config is:
<aecli settings>
  Epoch url _________________________________________ http://localhost:3013
</aecli settings>

And because I am pretty sure you are gonna ask, the epoch node is docker's 0.25 image connected to testnet.

**Comment by kryztoval** [comment]
internal endpoints are enabled, but they are, obviously, internal. And the internal endpoints are shared over a different port.

The external port and endpoints are all working, I can see any of the commands.

What am I exactly looking for?

**Comment by kryztoval** [comment]
BTW I did a name claim before this update (on 0.24.0-0.1.0) and it worked. And the internal ports were also internal. So there is something that changed in the last interaction and I want to know what did. Because it was not on my side.

**Comment by kryztoval** [comment]
Anything else I can try?

**Comment by noandrea** [comment]
did you set the `EPOCH_URL` env var by any chance?

I believe the issue you are having is just because the sdk in this case needs to use the internal endpoints but the address for the endpoints is incorrect because it defaults to the external endpoints when not set.

can you try using: 
```
aecli -u http://localhost:3013 -d http://localhost:3113 name claim wallet kryztoval.test
```

**Comment by kryztoval** [comment]
that works... So I am required to have internal ports available tot he computer that is running the aecli binary?

**Comment by noandrea** [comment]
@kryztoval currently it is necessary to have the internal ports available. 
And the env var for the internal endpoints is `EPOCH_URL_DEBUG`
