### ISSUE TITLE
Name claim does not work

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#95]
Name clain fails
Preclaim worked: th_2uf1posv6NshWtUC5Uva4QH7sMnAkUogQKfjQE5v5ZjZndJRq8

but then it crashed with
```
Traceback (most recent call last):
  File "./aecli", line 3, in <module>
    from aeternity import __main__
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 856, in <module>
    cli(obj={})
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 473, in name_register
    tx, tx_signed, sig, tx_hash = name.claim(account, fee, ttl)
  File "/opt/aepp-sdk-python/aeternity/aens.py", line 180, in claim
    self.client.broadcast_transaction(tx_signed, tx_hash)
  File "/opt/aepp-sdk-python/aeternity/epoch.py", line 143, in broadcast_transaction
    reply = self.post_transaction(body={"tx": tx})
  File "/opt/aepp-sdk-python/aeternity/openapi.py", line 207, in api_method
    raise OpenAPIClientException(f"Error: {api_response.desc}", code=http_reply.status_code)
aeternity.openapi.OpenAPIClientException: Error: Invalid transaction

```

I tried running it again, and it said this:
Traceback (most recent call last):
  File "/opt/aepp-sdk-python/aeternity/openapi.py", line 53, in __init__
    self.api_def = requests.get(f"{url}/api").json()
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "./aecli", line 3, in <module>
    from aeternity import __main__
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 856, in <module>
    cli(obj={})
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/aepp-sdk-python/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 458, in name_register
    name = _epoch_cli(network_id=network_id).AEName(domain)
  File "/opt/aepp-sdk-python/aeternity/__main__.py", line 54, in _epoch_cli
    native=native)
  File "/opt/aepp-sdk-python/aeternity/epoch.py", line 57, in __init__
    force_compatibility=force_compatibility)
  File "/opt/aepp-sdk-python/aeternity/openapi.py", line 65, in __init__
    raise UnsupportedEpochVersion(f"Unable to connect to the node: {e}")
aeternity.exceptions.UnsupportedEpochVersion: Unable to connect to the node: Expecting value: line 1 column 1 (char 0)
payload
None

```

Using the  405d7ddd0a39bf889303f5660098a55e9754518d commit

**Comment by kryztoval** [comment]
```
Traceback (most recent call last):
  File "./aecli", line 3, in <module>
    from aeternity import __main__
  File "/home/criesca/aepp-sdk-python/aeternity/__main__.py", line 857, in <module>
    cli(obj={})
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/criesca/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/criesca/aepp-sdk-python/aeternity/__main__.py", line 465, in name_register
    tx, tx_signed, sig, tx_hash = name.preclaim(account, fee, ttl)
  File "/home/criesca/aepp-sdk-python/aeternity/aens.py", line 160, in preclaim
    self.client.broadcast_transaction(tx_signed, tx_hash)
  File "/home/criesca/aepp-sdk-python/aeternity/epoch.py", line 146, in broadcast_transaction
    reply = self.post_transaction(body={"tx": tx})
  File "/home/criesca/aepp-sdk-python/aeternity/openapi.py", line 207, in api_method
    raise OpenAPIClientException(f"Error: {api_response.desc}", code=http_reply.status_code)
aeternity.openapi.OpenAPIClientException: Error: Invalid transaction
```

**Comment by kryztoval** [comment]
You need the right --network-id for this to work
